name = "adamr.io-theme"
license = "MIT"
licenselink = "https://github.com/msradam/adamr.io-theme/blob/master/LICENSE.md"
description = "A minimalist Hugo theme, customized for A. M. Rahman's website."
tags = ["blog", "clean", "customizable", "dark", "highlighting", "light", "minimal", "monochromatic", "multilingual", "personal", "responsive", "simple", "technical"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.30

[author]
  name = "Adam. Rahman"
  homepage = "https://atlialp.com"
  twitter = "https://twitter.com/rhazdon"

[original]
  name = "hello-friend"
  homepage = "https://github.com/panr/hugo-theme-hello-friend"
  repo = "https://github.com/panr/hugo-theme-hello-friend"
